version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - BASE_IMAGE=${BASE_IMAGE}  # 传递构建参数
        - INSTALL_PACKAGES=${INSTALL_PACKAGES}
    image: my-app:${APP_VERSION}    # 动态标签
    ports:
      - "${APP_PORT}:80"
    deploy:
      replicas: ${SERVICE_REPLICAS}
      