version: '3'

services:
  httpd:
    image: httpd:${HTTPD_TAG}
    container_name: ${NAME}
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./repo:/usr/local/apache2/htdocs/repo

networks:
  dev_net:
    driver: bridge

# version: '3'

# services:
#   httpd:
#     image: httpd:latest
#     container_name: my-httpd
#     ports:
#       - "80:80"
#     volumes:
#       - ./yum-repo:/usr/local/apache2/htdocs/yum-repo
#       - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
