version: '3'
services:
  gitea-server:
    build:
      context: ${GITEA_DOCKERFILE_DIR}
      dockerfile: ${GITEA_DOCKERFILE_NAME}
      args:
        buildno: 1
    # image: gitea/gitea:${GITEA_TAG}
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - HTTP_PORT=8080
    restart: always
    networks:
      - cicd
    volumes:
      - ${GITEA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:8080"
      - "${GITEA_SSH_PORT}:22"
    # extra_hosts:
    #   - "${SERVICE_DOMAIN}:127.0.0.1"

  drone-server:
    restart: always
    image: drone/drone:${DRONE_TAG}
    ports:
      - "${DRONE_PORT}:80"
    networks:
      - cicd
    volumes:
      - ./:/var/lib/drone/
      - ${DRONE_PATH}:/data/
    environment:
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER} # Gitea访问地址
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID} # 应用ID,下一步会获取
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET} # 应用密钥,下一步会获取
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=http # 支持http, https
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET} # 通信密钥,下一步会获取
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GIT_USERNAME=${DRONE_GIT_USERNAME} # git用户名
      - DRONE_GIT_PASSWORD=${DRONE_GIT_USERNAME} # git密码
      - DRONE_USER_CREATE=username:${DRONE_GIT_USERNAME},admin:true # 管理员用户名,开启管理员账户
  drone-runner-docker:
    networks:
      - cicd
    restart: always
    image: drone/drone-runner-docker:${DRONE_RUNER_DOCKER_TAG}
    ports:
      - "${DRONE_RUNER_DOCKER_PORT}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http # 支持http, https
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET} # 通信密钥,下一步会获取
      - DRONE_RUNNER_NAME=drone-runner-docker
      - DRONE_RUNNER_CAPACITY=2

networks:
  cicd:
    external: true