version: '3.8'

networks:
  internal_net:
    driver: bridge
    # internal: true  # 禁止外部访问 # 会新建内部网络
    name: internal_net  # 强制指向现有网络
  share_net:
    external: true
    name: share_net  # 强制指向现有网络
  
services:
  server:
    build:
      context: .
      dockerfile: gitea.dockerfile
      args:
        - GITEA_VERSION=${GITEA_VERSION}
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - internal_net
      - share_net
    volumes:
      - ${GITEA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"